apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      name: django-cluster
  template:
    metadata:
      labels:
        name: django-cluster
        cluster_name: django-cluster
    # GCP Kubernetes Engine ワークロードにデプロイ
    spec:
      containers:
      - name: django-cluster
        image: gcr.io/jointparty/django-cluster:latest
        # envFrom:
        # - secretRef:
        #   name: joint-env
        ports:
        - containerPort: 8080
          protocol: TCP
    # spec:
    #   containers:
    #   - name: django-cluster
    #     image: gcr.io/jointparty/nginx/django-cluster:latest
    #     ports:
    #     - containerPort: 8000 #8080
    #       protocol: TCP

    # spec:
    #   containers:
    #   - name: nginx
    #     image: nginx:1.17.4
    #     ports:
    #     - containerPort: 8000
      
  revisionHistoryLimit: 100
