apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: django-cluster
  template:
    metadata:
      labels:
        name: django-cluster
        cluster_name: django-cluster
    spec:
      containers:
      - name: django-cluster
        image: gcr.io/jointparty/django-cluster:latest
        # envFrom:
        # - secretRef:
        #   name: joint-env
        ports:
        - containerPort: 8000 #8080
          protocol: TCP
      # - restartPolicy: OnFailure
  containers:
  - name:
    image:
    env:
    - name: SECRET_KEY
      value: =llv2rzj$^vk)wx7n_u9v$o(ic2i-7w)m&0il3vlamiei2#&d6
  revisionHistoryLimit: 100
