apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  SECRET_KEY: PWxsdjJyemokXnZrKXd4N25fdTl2JG8oaWMyaS03dyltJjBpbDN2bGFtaWVpMiMmZDY=
  ALLOWED_HOSTS: bG9jYWxob3N0IDEyNy4wLjAuMQ==
  DEBUG: MA==