# Generated by Django 3.0 on 2019-12-26 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.UserInfo')),
            ],
        ),
    ]
