# Generated by Django 3.0 on 2019-12-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='match.Image'),
            preserve_default=False,
        ),
    ]
