# Generated by Django 3.0 on 2020-01-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_chatmessage_chatroom_chatroomuser_posts_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='approval',
            field=models.IntegerField(default=0),
        ),
    ]
