# Generated by Django 3.0 on 2019-12-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='match.UserInfo')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='told', to='match.Posts')),
            ],
        ),
    ]
